s1=input("enter a string ")
b=int(input("starting index for slicing"))
e=int(input("ending index for slicing"))
n=len(s1)
print("\nin upper case ")
print(s1.upper())
print("\nin lower case ")
print(s1.lower())
print("\nafter slicing  ")
print(s1[b:e])
print("\nReversed String is")
print(s1[n::-1])